package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudSysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.id
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.transcode
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String transcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.class_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.function_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String functionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.request_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.response_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private Date responseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.system_ip
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String systemIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.system_port
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String systemPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.time_consum
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private Integer timeConsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.request_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String requestData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_log.response_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    private String responseData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.id
     *
     * @return the value of es_cloud_sys_log.id
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.id
     *
     * @param id the value for es_cloud_sys_log.id
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.transcode
     *
     * @return the value of es_cloud_sys_log.transcode
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.transcode
     *
     * @param transcode the value for es_cloud_sys_log.transcode
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.class_name
     *
     * @return the value of es_cloud_sys_log.class_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.class_name
     *
     * @param className the value for es_cloud_sys_log.class_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.function_name
     *
     * @return the value of es_cloud_sys_log.function_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.function_name
     *
     * @param functionName the value for es_cloud_sys_log.function_name
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.request_time
     *
     * @return the value of es_cloud_sys_log.request_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.request_time
     *
     * @param requestTime the value for es_cloud_sys_log.request_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.response_time
     *
     * @return the value of es_cloud_sys_log.response_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.response_time
     *
     * @param responseTime the value for es_cloud_sys_log.response_time
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.system_ip
     *
     * @return the value of es_cloud_sys_log.system_ip
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getSystemIp() {
        return systemIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.system_ip
     *
     * @param systemIp the value for es_cloud_sys_log.system_ip
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setSystemIp(String systemIp) {
        this.systemIp = systemIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.system_port
     *
     * @return the value of es_cloud_sys_log.system_port
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getSystemPort() {
        return systemPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.system_port
     *
     * @param systemPort the value for es_cloud_sys_log.system_port
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setSystemPort(String systemPort) {
        this.systemPort = systemPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.time_consum
     *
     * @return the value of es_cloud_sys_log.time_consum
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public Integer getTimeConsum() {
        return timeConsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.time_consum
     *
     * @param timeConsum the value for es_cloud_sys_log.time_consum
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setTimeConsum(Integer timeConsum) {
        this.timeConsum = timeConsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.request_data
     *
     * @return the value of es_cloud_sys_log.request_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getRequestData() {
        return requestData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.request_data
     *
     * @param requestData the value for es_cloud_sys_log.request_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setRequestData(String requestData) {
        this.requestData = requestData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_log.response_data
     *
     * @return the value of es_cloud_sys_log.response_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getResponseData() {
        return responseData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_log.response_data
     *
     * @param responseData the value for es_cloud_sys_log.response_data
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setResponseData(String responseData) {
        this.responseData = responseData;
    }
}