package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudSysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.id
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.scode
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.stype
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.svalue
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String svalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.islock
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String islock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.createdate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.createuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.updatedate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.updateuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_sys_config.remark
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.id
     *
     * @return the value of es_cloud_sys_config.id
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.id
     *
     * @param id the value for es_cloud_sys_config.id
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.scode
     *
     * @return the value of es_cloud_sys_config.scode
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.scode
     *
     * @param scode the value for es_cloud_sys_config.scode
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.stype
     *
     * @return the value of es_cloud_sys_config.stype
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.stype
     *
     * @param stype the value for es_cloud_sys_config.stype
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setStype(String stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.svalue
     *
     * @return the value of es_cloud_sys_config.svalue
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getSvalue() {
        return svalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.svalue
     *
     * @param svalue the value for es_cloud_sys_config.svalue
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setSvalue(String svalue) {
        this.svalue = svalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.islock
     *
     * @return the value of es_cloud_sys_config.islock
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.islock
     *
     * @param islock the value for es_cloud_sys_config.islock
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setIslock(String islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.createdate
     *
     * @return the value of es_cloud_sys_config.createdate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.createdate
     *
     * @param createdate the value for es_cloud_sys_config.createdate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.createuser
     *
     * @return the value of es_cloud_sys_config.createuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.createuser
     *
     * @param createuser the value for es_cloud_sys_config.createuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.updatedate
     *
     * @return the value of es_cloud_sys_config.updatedate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.updatedate
     *
     * @param updatedate the value for es_cloud_sys_config.updatedate
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.updateuser
     *
     * @return the value of es_cloud_sys_config.updateuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.updateuser
     *
     * @param updateuser the value for es_cloud_sys_config.updateuser
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_sys_config.remark
     *
     * @return the value of es_cloud_sys_config.remark
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_sys_config.remark
     *
     * @param remark the value for es_cloud_sys_config.remark
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}