package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.anth_id
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    private String anthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.auth_name
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.parentid
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.auth_type
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.auth_sort
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private Integer authSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.auth_link
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String authLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_authority.remark
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.anth_id
     *
     * @return the value of es_cloud_authority.anth_id
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    public String getAnthId() {
        return anthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.anth_id
     *
     * @param anthId the value for es_cloud_authority.anth_id
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    public void setAnthId(String anthId) {
        this.anthId = anthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.auth_name
     *
     * @return the value of es_cloud_authority.auth_name
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.auth_name
     *
     * @param authName the value for es_cloud_authority.auth_name
     *
     * @mbg.generated Tue Aug 08 17:18:40 CST 2017
     */
    public void setAuthName(String authName) {
        this.authName = authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.parentid
     *
     * @return the value of es_cloud_authority.parentid
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.parentid
     *
     * @param parentid the value for es_cloud_authority.parentid
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.auth_type
     *
     * @return the value of es_cloud_authority.auth_type
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.auth_type
     *
     * @param authType the value for es_cloud_authority.auth_type
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.auth_sort
     *
     * @return the value of es_cloud_authority.auth_sort
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public Integer getAuthSort() {
        return authSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.auth_sort
     *
     * @param authSort the value for es_cloud_authority.auth_sort
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setAuthSort(Integer authSort) {
        this.authSort = authSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.auth_link
     *
     * @return the value of es_cloud_authority.auth_link
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getAuthLink() {
        return authLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.auth_link
     *
     * @param authLink the value for es_cloud_authority.auth_link
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setAuthLink(String authLink) {
        this.authLink = authLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.createdate
     *
     * @return the value of es_cloud_authority.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.createdate
     *
     * @param createdate the value for es_cloud_authority.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.createuser
     *
     * @return the value of es_cloud_authority.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.createuser
     *
     * @param createuser the value for es_cloud_authority.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.updatedate
     *
     * @return the value of es_cloud_authority.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.updatedate
     *
     * @param updatedate the value for es_cloud_authority.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.updateuser
     *
     * @return the value of es_cloud_authority.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.updateuser
     *
     * @param updateuser the value for es_cloud_authority.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_authority.remark
     *
     * @return the value of es_cloud_authority.remark
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_authority.remark
     *
     * @param remark the value for es_cloud_authority.remark
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}