package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.role_no
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.role_name
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.role_sort
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private Integer roleSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.islock
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String islock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.id
     *
     * @return the value of es_cloud_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.id
     *
     * @param id the value for es_cloud_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.role_no
     *
     * @return the value of es_cloud_role.role_no
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.role_no
     *
     * @param roleNo the value for es_cloud_role.role_no
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.role_name
     *
     * @return the value of es_cloud_role.role_name
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.role_name
     *
     * @param roleName the value for es_cloud_role.role_name
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.role_sort
     *
     * @return the value of es_cloud_role.role_sort
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public Integer getRoleSort() {
        return roleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.role_sort
     *
     * @param roleSort the value for es_cloud_role.role_sort
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setRoleSort(Integer roleSort) {
        this.roleSort = roleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.islock
     *
     * @return the value of es_cloud_role.islock
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.islock
     *
     * @param islock the value for es_cloud_role.islock
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setIslock(String islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.createdate
     *
     * @return the value of es_cloud_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.createdate
     *
     * @param createdate the value for es_cloud_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.createuser
     *
     * @return the value of es_cloud_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.createuser
     *
     * @param createuser the value for es_cloud_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.updatedate
     *
     * @return the value of es_cloud_role.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.updatedate
     *
     * @param updatedate the value for es_cloud_role.updatedate
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role.updateuser
     *
     * @return the value of es_cloud_role.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role.updateuser
     *
     * @param updateuser the value for es_cloud_role.updateuser
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }
}