package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudOrg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_id
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_long_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String orgLongName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_level
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String orgLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_sort
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private Integer orgSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.org_status
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String orgStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.parentid
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.createdate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.createuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.updatedate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org.updateuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_id
     *
     * @return the value of es_cloud_org.org_id
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_id
     *
     * @param orgId the value for es_cloud_org.org_id
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_name
     *
     * @return the value of es_cloud_org.org_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_name
     *
     * @param orgName the value for es_cloud_org.org_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_long_name
     *
     * @return the value of es_cloud_org.org_long_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getOrgLongName() {
        return orgLongName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_long_name
     *
     * @param orgLongName the value for es_cloud_org.org_long_name
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgLongName(String orgLongName) {
        this.orgLongName = orgLongName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_level
     *
     * @return the value of es_cloud_org.org_level
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_level
     *
     * @param orgLevel the value for es_cloud_org.org_level
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgLevel(String orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_sort
     *
     * @return the value of es_cloud_org.org_sort
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public Integer getOrgSort() {
        return orgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_sort
     *
     * @param orgSort the value for es_cloud_org.org_sort
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgSort(Integer orgSort) {
        this.orgSort = orgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.org_status
     *
     * @return the value of es_cloud_org.org_status
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getOrgStatus() {
        return orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.org_status
     *
     * @param orgStatus the value for es_cloud_org.org_status
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setOrgStatus(String orgStatus) {
        this.orgStatus = orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.parentid
     *
     * @return the value of es_cloud_org.parentid
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.parentid
     *
     * @param parentid the value for es_cloud_org.parentid
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.createdate
     *
     * @return the value of es_cloud_org.createdate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.createdate
     *
     * @param createdate the value for es_cloud_org.createdate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.createuser
     *
     * @return the value of es_cloud_org.createuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.createuser
     *
     * @param createuser the value for es_cloud_org.createuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.updatedate
     *
     * @return the value of es_cloud_org.updatedate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.updatedate
     *
     * @param updatedate the value for es_cloud_org.updatedate
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org.updateuser
     *
     * @return the value of es_cloud_org.updateuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org.updateuser
     *
     * @param updateuser the value for es_cloud_org.updateuser
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }
}