package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudOperRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_oper_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_oper_role.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_oper_role.oper_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    private String operId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_oper_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_oper_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_oper_role.id
     *
     * @return the value of es_cloud_oper_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_oper_role.id
     *
     * @param id the value for es_cloud_oper_role.id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_oper_role.role_id
     *
     * @return the value of es_cloud_oper_role.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_oper_role.role_id
     *
     * @param roleId the value for es_cloud_oper_role.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_oper_role.oper_id
     *
     * @return the value of es_cloud_oper_role.oper_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_oper_role.oper_id
     *
     * @param operId the value for es_cloud_oper_role.oper_id
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public void setOperId(String operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_oper_role.createdate
     *
     * @return the value of es_cloud_oper_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_oper_role.createdate
     *
     * @param createdate the value for es_cloud_oper_role.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_oper_role.createuser
     *
     * @return the value of es_cloud_oper_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_oper_role.createuser
     *
     * @param createuser the value for es_cloud_oper_role.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }
}