package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudRoleAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role_auth.id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role_auth.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role_auth.auth_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    private String authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role_auth.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_role_auth.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role_auth.id
     *
     * @return the value of es_cloud_role_auth.id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role_auth.id
     *
     * @param id the value for es_cloud_role_auth.id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role_auth.role_id
     *
     * @return the value of es_cloud_role_auth.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role_auth.role_id
     *
     * @param roleId the value for es_cloud_role_auth.role_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role_auth.auth_id
     *
     * @return the value of es_cloud_role_auth.auth_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role_auth.auth_id
     *
     * @param authId the value for es_cloud_role_auth.auth_id
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role_auth.createdate
     *
     * @return the value of es_cloud_role_auth.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role_auth.createdate
     *
     * @param createdate the value for es_cloud_role_auth.createdate
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_role_auth.createuser
     *
     * @return the value of es_cloud_role_auth.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_role_auth.createuser
     *
     * @param createuser the value for es_cloud_role_auth.createuser
     *
     * @mbg.generated Tue Aug 08 17:18:51 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }
}