package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EsCloudSysLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public EsCloudSysLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTranscodeIsNull() {
            addCriterion("transcode is null");
            return (Criteria) this;
        }

        public Criteria andTranscodeIsNotNull() {
            addCriterion("transcode is not null");
            return (Criteria) this;
        }

        public Criteria andTranscodeEqualTo(String value) {
            addCriterion("transcode =", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeNotEqualTo(String value) {
            addCriterion("transcode <>", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeGreaterThan(String value) {
            addCriterion("transcode >", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeGreaterThanOrEqualTo(String value) {
            addCriterion("transcode >=", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeLessThan(String value) {
            addCriterion("transcode <", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeLessThanOrEqualTo(String value) {
            addCriterion("transcode <=", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeLike(String value) {
            addCriterion("transcode like", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeNotLike(String value) {
            addCriterion("transcode not like", value, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeIn(List<String> values) {
            addCriterion("transcode in", values, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeNotIn(List<String> values) {
            addCriterion("transcode not in", values, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeBetween(String value1, String value2) {
            addCriterion("transcode between", value1, value2, "transcode");
            return (Criteria) this;
        }

        public Criteria andTranscodeNotBetween(String value1, String value2) {
            addCriterion("transcode not between", value1, value2, "transcode");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNull() {
            addCriterion("function_name is null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNotNull() {
            addCriterion("function_name is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameEqualTo(String value) {
            addCriterion("function_name =", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotEqualTo(String value) {
            addCriterion("function_name <>", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThan(String value) {
            addCriterion("function_name >", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThanOrEqualTo(String value) {
            addCriterion("function_name >=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThan(String value) {
            addCriterion("function_name <", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThanOrEqualTo(String value) {
            addCriterion("function_name <=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLike(String value) {
            addCriterion("function_name like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotLike(String value) {
            addCriterion("function_name not like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIn(List<String> values) {
            addCriterion("function_name in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotIn(List<String> values) {
            addCriterion("function_name not in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameBetween(String value1, String value2) {
            addCriterion("function_name between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotBetween(String value1, String value2) {
            addCriterion("function_name not between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNull() {
            addCriterion("request_time is null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNotNull() {
            addCriterion("request_time is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeEqualTo(Date value) {
            addCriterion("request_time =", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotEqualTo(Date value) {
            addCriterion("request_time <>", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThan(Date value) {
            addCriterion("request_time >", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("request_time >=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThan(Date value) {
            addCriterion("request_time <", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThanOrEqualTo(Date value) {
            addCriterion("request_time <=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIn(List<Date> values) {
            addCriterion("request_time in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotIn(List<Date> values) {
            addCriterion("request_time not in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeBetween(Date value1, Date value2) {
            addCriterion("request_time between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotBetween(Date value1, Date value2) {
            addCriterion("request_time not between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIsNull() {
            addCriterion("response_time is null");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIsNotNull() {
            addCriterion("response_time is not null");
            return (Criteria) this;
        }

        public Criteria andResponseTimeEqualTo(Date value) {
            addCriterion("response_time =", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotEqualTo(Date value) {
            addCriterion("response_time <>", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeGreaterThan(Date value) {
            addCriterion("response_time >", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("response_time >=", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeLessThan(Date value) {
            addCriterion("response_time <", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeLessThanOrEqualTo(Date value) {
            addCriterion("response_time <=", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIn(List<Date> values) {
            addCriterion("response_time in", values, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotIn(List<Date> values) {
            addCriterion("response_time not in", values, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeBetween(Date value1, Date value2) {
            addCriterion("response_time between", value1, value2, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotBetween(Date value1, Date value2) {
            addCriterion("response_time not between", value1, value2, "responseTime");
            return (Criteria) this;
        }

        public Criteria andSystemIpIsNull() {
            addCriterion("system_ip is null");
            return (Criteria) this;
        }

        public Criteria andSystemIpIsNotNull() {
            addCriterion("system_ip is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIpEqualTo(String value) {
            addCriterion("system_ip =", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpNotEqualTo(String value) {
            addCriterion("system_ip <>", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpGreaterThan(String value) {
            addCriterion("system_ip >", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpGreaterThanOrEqualTo(String value) {
            addCriterion("system_ip >=", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpLessThan(String value) {
            addCriterion("system_ip <", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpLessThanOrEqualTo(String value) {
            addCriterion("system_ip <=", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpLike(String value) {
            addCriterion("system_ip like", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpNotLike(String value) {
            addCriterion("system_ip not like", value, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpIn(List<String> values) {
            addCriterion("system_ip in", values, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpNotIn(List<String> values) {
            addCriterion("system_ip not in", values, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpBetween(String value1, String value2) {
            addCriterion("system_ip between", value1, value2, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemIpNotBetween(String value1, String value2) {
            addCriterion("system_ip not between", value1, value2, "systemIp");
            return (Criteria) this;
        }

        public Criteria andSystemPortIsNull() {
            addCriterion("system_port is null");
            return (Criteria) this;
        }

        public Criteria andSystemPortIsNotNull() {
            addCriterion("system_port is not null");
            return (Criteria) this;
        }

        public Criteria andSystemPortEqualTo(String value) {
            addCriterion("system_port =", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortNotEqualTo(String value) {
            addCriterion("system_port <>", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortGreaterThan(String value) {
            addCriterion("system_port >", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortGreaterThanOrEqualTo(String value) {
            addCriterion("system_port >=", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortLessThan(String value) {
            addCriterion("system_port <", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortLessThanOrEqualTo(String value) {
            addCriterion("system_port <=", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortLike(String value) {
            addCriterion("system_port like", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortNotLike(String value) {
            addCriterion("system_port not like", value, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortIn(List<String> values) {
            addCriterion("system_port in", values, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortNotIn(List<String> values) {
            addCriterion("system_port not in", values, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortBetween(String value1, String value2) {
            addCriterion("system_port between", value1, value2, "systemPort");
            return (Criteria) this;
        }

        public Criteria andSystemPortNotBetween(String value1, String value2) {
            addCriterion("system_port not between", value1, value2, "systemPort");
            return (Criteria) this;
        }

        public Criteria andTimeConsumIsNull() {
            addCriterion("time_consum is null");
            return (Criteria) this;
        }

        public Criteria andTimeConsumIsNotNull() {
            addCriterion("time_consum is not null");
            return (Criteria) this;
        }

        public Criteria andTimeConsumEqualTo(Integer value) {
            addCriterion("time_consum =", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumNotEqualTo(Integer value) {
            addCriterion("time_consum <>", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumGreaterThan(Integer value) {
            addCriterion("time_consum >", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_consum >=", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumLessThan(Integer value) {
            addCriterion("time_consum <", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumLessThanOrEqualTo(Integer value) {
            addCriterion("time_consum <=", value, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumIn(List<Integer> values) {
            addCriterion("time_consum in", values, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumNotIn(List<Integer> values) {
            addCriterion("time_consum not in", values, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumBetween(Integer value1, Integer value2) {
            addCriterion("time_consum between", value1, value2, "timeConsum");
            return (Criteria) this;
        }

        public Criteria andTimeConsumNotBetween(Integer value1, Integer value2) {
            addCriterion("time_consum not between", value1, value2, "timeConsum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 08 17:19:14 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}