package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudOrgOper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org_oper.id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org_oper.org_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org_oper.oper_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    private String operId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org_oper.createdate
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_org_oper.createuser
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org_oper.id
     *
     * @return the value of es_cloud_org_oper.id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org_oper.id
     *
     * @param id the value for es_cloud_org_oper.id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org_oper.org_id
     *
     * @return the value of es_cloud_org_oper.org_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org_oper.org_id
     *
     * @param orgId the value for es_cloud_org_oper.org_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org_oper.oper_id
     *
     * @return the value of es_cloud_org_oper.oper_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org_oper.oper_id
     *
     * @param operId the value for es_cloud_org_oper.oper_id
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public void setOperId(String operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org_oper.createdate
     *
     * @return the value of es_cloud_org_oper.createdate
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org_oper.createdate
     *
     * @param createdate the value for es_cloud_org_oper.createdate
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_org_oper.createuser
     *
     * @return the value of es_cloud_org_oper.createuser
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_org_oper.createuser
     *
     * @param createuser the value for es_cloud_org_oper.createuser
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }
}