package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity;

import java.util.Date;

public class EsCloudOperator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.id
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.username
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.password
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.salt
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.birthday
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.sex
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.idtype
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String idtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.idno
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String idno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.postaddress
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String postaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.islock
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String islock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.createdate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.createuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.updatedate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es_cloud_operator.updateuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.id
     *
     * @return the value of es_cloud_operator.id
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.id
     *
     * @param id the value for es_cloud_operator.id
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.username
     *
     * @return the value of es_cloud_operator.username
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.username
     *
     * @param username the value for es_cloud_operator.username
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.password
     *
     * @return the value of es_cloud_operator.password
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.password
     *
     * @param password the value for es_cloud_operator.password
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.salt
     *
     * @return the value of es_cloud_operator.salt
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.salt
     *
     * @param salt the value for es_cloud_operator.salt
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.birthday
     *
     * @return the value of es_cloud_operator.birthday
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.birthday
     *
     * @param birthday the value for es_cloud_operator.birthday
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.sex
     *
     * @return the value of es_cloud_operator.sex
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.sex
     *
     * @param sex the value for es_cloud_operator.sex
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.idtype
     *
     * @return the value of es_cloud_operator.idtype
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.idtype
     *
     * @param idtype the value for es_cloud_operator.idtype
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.idno
     *
     * @return the value of es_cloud_operator.idno
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.idno
     *
     * @param idno the value for es_cloud_operator.idno
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.postaddress
     *
     * @return the value of es_cloud_operator.postaddress
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getPostaddress() {
        return postaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.postaddress
     *
     * @param postaddress the value for es_cloud_operator.postaddress
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setPostaddress(String postaddress) {
        this.postaddress = postaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.islock
     *
     * @return the value of es_cloud_operator.islock
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.islock
     *
     * @param islock the value for es_cloud_operator.islock
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setIslock(String islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.createdate
     *
     * @return the value of es_cloud_operator.createdate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.createdate
     *
     * @param createdate the value for es_cloud_operator.createdate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.createuser
     *
     * @return the value of es_cloud_operator.createuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.createuser
     *
     * @param createuser the value for es_cloud_operator.createuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.updatedate
     *
     * @return the value of es_cloud_operator.updatedate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.updatedate
     *
     * @param updatedate the value for es_cloud_operator.updatedate
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_cloud_operator.updateuser
     *
     * @return the value of es_cloud_operator.updateuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_cloud_operator.updateuser
     *
     * @param updateuser the value for es_cloud_operator.updateuser
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }
}