package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOperator;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOperatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    long countByExample(EsCloudOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int deleteByExample(EsCloudOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int insert(EsCloudOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int insertSelective(EsCloudOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    List<EsCloudOperator> selectByExample(EsCloudOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    EsCloudOperator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudOperator record, @Param("example") EsCloudOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int updateByExample(@Param("record") EsCloudOperator record, @Param("example") EsCloudOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_operator
     *
     * @mbg.generated Tue Aug 08 17:16:43 CST 2017
     */
    int updateByPrimaryKey(EsCloudOperator record);
}