package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudSysConfig;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudSysConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudSysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    long countByExample(EsCloudSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int deleteByExample(EsCloudSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int insert(EsCloudSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int insertSelective(EsCloudSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    List<EsCloudSysConfig> selectByExample(EsCloudSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    EsCloudSysConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudSysConfig record, @Param("example") EsCloudSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int updateByExample(@Param("record") EsCloudSysConfig record, @Param("example") EsCloudSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_config
     *
     * @mbg.generated Tue Aug 08 17:19:03 CST 2017
     */
    int updateByPrimaryKey(EsCloudSysConfig record);
}