package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudAuthority;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    long countByExample(EsCloudAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int deleteByExample(EsCloudAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int deleteByPrimaryKey(String anthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int insert(EsCloudAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int insertSelective(EsCloudAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    List<EsCloudAuthority> selectByExample(EsCloudAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    EsCloudAuthority selectByPrimaryKey(String anthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudAuthority record, @Param("example") EsCloudAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int updateByExample(@Param("record") EsCloudAuthority record, @Param("example") EsCloudAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_authority
     *
     * @mbg.generated Tue Aug 08 17:18:41 CST 2017
     */
    int updateByPrimaryKey(EsCloudAuthority record);
}