package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOperRole;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOperRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudOperRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    long countByExample(EsCloudOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int deleteByExample(EsCloudOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int insert(EsCloudOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int insertSelective(EsCloudOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    List<EsCloudOperRole> selectByExample(EsCloudOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    EsCloudOperRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudOperRole record, @Param("example") EsCloudOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int updateByExample(@Param("record") EsCloudOperRole record, @Param("example") EsCloudOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_oper_role
     *
     * @mbg.generated Tue Aug 08 17:18:29 CST 2017
     */
    int updateByPrimaryKey(EsCloudOperRole record);
}