package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudRole;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    long countByExample(EsCloudRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int deleteByExample(EsCloudRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int insert(EsCloudRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int insertSelective(EsCloudRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    List<EsCloudRole> selectByExample(EsCloudRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    EsCloudRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudRole record, @Param("example") EsCloudRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int updateByExample(@Param("record") EsCloudRole record, @Param("example") EsCloudRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_role
     *
     * @mbg.generated Tue Aug 08 17:18:18 CST 2017
     */
    int updateByPrimaryKey(EsCloudRole record);
}