package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOrgOper;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOrgOperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudOrgOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    long countByExample(EsCloudOrgOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int deleteByExample(EsCloudOrgOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int insert(EsCloudOrgOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int insertSelective(EsCloudOrgOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    List<EsCloudOrgOper> selectByExample(EsCloudOrgOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    EsCloudOrgOper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudOrgOper record, @Param("example") EsCloudOrgOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int updateByExample(@Param("record") EsCloudOrgOper record, @Param("example") EsCloudOrgOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudOrgOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org_oper
     *
     * @mbg.generated Tue Aug 08 17:17:15 CST 2017
     */
    int updateByPrimaryKey(EsCloudOrgOper record);
}