package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudSysLog;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudSysLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudSysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    long countByExample(EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int deleteByExample(EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int insert(EsCloudSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int insertSelective(EsCloudSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    List<EsCloudSysLog> selectByExampleWithBLOBs(EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    List<EsCloudSysLog> selectByExample(EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    EsCloudSysLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudSysLog record, @Param("example") EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") EsCloudSysLog record, @Param("example") EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByExample(@Param("record") EsCloudSysLog record, @Param("example") EsCloudSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(EsCloudSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_sys_log
     *
     * @mbg.generated Tue Aug 08 17:19:14 CST 2017
     */
    int updateByPrimaryKey(EsCloudSysLog record);
}