package com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.mapper;

import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOrg;
import com.fq.ebusiness.pms.common.dao.modules.pro.mybatis.entity.EsCloudOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsCloudOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    long countByExample(EsCloudOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int deleteByExample(EsCloudOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int deleteByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int insert(EsCloudOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int insertSelective(EsCloudOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    List<EsCloudOrg> selectByExample(EsCloudOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    EsCloudOrg selectByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsCloudOrg record, @Param("example") EsCloudOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int updateByExample(@Param("record") EsCloudOrg record, @Param("example") EsCloudOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int updateByPrimaryKeySelective(EsCloudOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_cloud_org
     *
     * @mbg.generated Tue Aug 08 17:06:34 CST 2017
     */
    int updateByPrimaryKey(EsCloudOrg record);
}